name: Remote Dispatch Action Responder
 
on: [repository_dispatch]
 
jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.github_repository }}
          ref: ${{ github.event.client_payload.github_ref }}
          token: ${{ secrets[github.event.client_payload.ping_access_token] }}

      - name: Caching Dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ github.event.client_payload.github_repository }}-${{ github.event.client_payload.github_ref }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.event.client_payload.github_repository }}-${{ github.event.client_payload.github_ref }}-
            ${{ runner.os }}-${{ github.event.client_payload.github_repository }}-
            ${{ runner.os }}-

      - name: Install your dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn lint
